### PR TITLE
Feature meth 479 portrait archive layout

### PR DESCRIPTION
**Pull request by dvdn**
Needs a 'portrait' model to be tested

### CODE REVIEW

**Comment by dvdn** [comment]
:dizzy_face: As crazy as it is, rendering thru pdfGenerator DEV didn't gave me same results as my local instance (fresh clone, untouched).
Last css adaptation is in this way.

**Comment by vinzentt** [comment]
Beware of your packages versions, qt, xfvb, wkhtml etc

**Comment by dvdn** [comment]
Nice though.
We need to clear this (fix versions ?) to avoid possible problem on different platforms.

**Comment by vinzentt** [comment]
We should follow what is on the production servers, ie stable version for those packages for the debian distribution used by the run team.

**Pull request merged**
