### PR TITLE
hotfix-bad-season-pdfs-link

### PR DESCRIPTION
**Pull request by dvdn**
bad default case displaying always 'area' link
Landing page from a network

### CODE REVIEW

**Comment by vinzentt** [comment]
IMO this PR won't fix the link pb on tt homepage, check the twig but for seasons there is no link displayed at all in the actions column

**Comment by vinzentt** [comment]
Ok it may happen if a season has the same id as a area. Anyway it´s better to do like you do.

**Comment by datanel** [comment]
tests broken

**Comment by dvdn** [comment]
Jenkins can you test this please

**Comment by Netmisa** [comment]
Test broken ?

**Pull request merged**
