### PR TITLE
Configuration of area entity in yml updated for worker caching.

### PR DESCRIPTION
**Pull request by Netmisa**
#METH-465

### CODE REVIEW

**Comment by vinzentt** [comment]
Ok for me, I had the same pb when generating pdf for a season. Only warning, I don't have a timetable instance to check if the bug is really fixed.

**Comment by Netmisa** [comment]
Thanks @vinzentt, I will poke @dvdn

**Comment by Netmisa** [comment]
Jenkins, could you test this please ?

**Comment by dvdn** [comment]
Can't test / lack of local config setup to be able to generate pdf from 'MQ dev. server

**Pull request merged**
